### ISSUE TITLE
`./bin/build` を実行すると `Could not locate Gemfile` というエラーが出る

### ISSUE THREAD

**Issue by kdnakt** [quarkusio/ja.quarkus.io#1021]
ローカルで修正した翻訳の変更結果を確認するため、`./bin/build` を実行したのですが、
`Could not locate Gemfile` というエラーが表示されました。

期待結果としては、README.mdの `Build a localized site locally` のセクションに記載されているとおり、
`doc` ディレクトリに変更後のhtmlが生成されることです。

事前に `./bin/setup-build-env` コマンドは実行済ですが、何か追加で実行すべきコマンドがありますでしょうか...

**Comment by megascus** [comment]
ちょっとそちらの原因はこれから調べるのですが、Pull Requestを出していただけると、サーバー側でビルドされて確認ができます。
他のチケットを見るとドラフト状態のPRを出して確認してからマージする手順になってるのがわかるので、そういった形でお願いできないでしょうか。
https://github.com/quarkusio/ja.quarkus.io/pull/663

**Comment by megascus** [comment]
翻訳ガイドを確認したのですが、以下のような記載になっていました。ので、先ほど案内した手順の方がよさそうです。

```
翻訳結果のプレビュー
.poファイルを翻訳し、Pull-Requestを頂ければ、自動でGitHub Actionsでサイトのビルドが行われ、一時的にサイトを閲覧できるURLが GitHubのPull-Requestに対するコメントとして5分程度で送信されます。 そちらの一時サイトから、翻訳結果のプレビューを確認することが出来ますので、ご活用下さい。
```

./bin/build を呼び出す手順がミスってる気がするので、どちらに記載があったか教えてもらってもよろしいですか？

**Comment by kdnakt** [comment]
ご回答ありがとうございます。
ドラフトPRの件承知しました。そちらの手順で進めるようにします。

./bin/buildを呼び出したのは、
README.mdの `Build a localized site locally` のところでローカルでビルドしたHTMLを確認するためのコマンドが
```
bin/apply-translation
bin/exec-jekyll
```
と書かれており、./bin/buildで同じコマンドが実行されていたので、./bin/buildを実行しても同じかな、と勝手に判断して実行してしまいました。
どこかに明示的に書かれていたわけではありません 🙇

**Comment by megascus** [comment]
ありがとうございます。トップページ部分のあれかー。。。
