### ISSUE TITLE
Missing redirection from http to https

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/ja.quarkus.io#1105]
If I go to http://ja.quarkus.io/, I don't get redirected to https://ja.quarkus.io/ .

On the other hand, http://quarkus.io/ and http://es.quarkus.io/ and http://pt.quarkus.io/ do redirect to their HTTPS equivalent.

Is this an oversight?

* If so this probably needs to be fixed. 
* Otherwise we'll need to update CORS rules on https://github.com/quarkusio/search.quarkus.io to allow HTTP, because guide search won't work on HTTP without it (see https://github.com/quarkusio/ja.quarkus.io/issues/1104#issuecomment-1903739022).

See also https://github.com/quarkusio/cn.quarkus.io/issues/223

**Comment by yrodiere** [comment]
If you use GitHub pages, I think this should fix it: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

**Comment by ynojima** [comment]
Thank you for pointing out! 
Now the HTTPS is enforced on ja.quarkus.io too.
