### ISSUE TITLE
GitHub Actions scheduler settings in 'build' workflow

### ISSUE THREAD

**Issue by tadayosi** [quarkusio/ja.quarkus.io#338]
Doesn't this mean a task to be run every minute in 9 o'clock?  Unlike the comment is it the real intention?
https://github.com/quarkusio/ja.quarkus.io/blob/master/.github/workflows/build.yml#L9
```
  schedule:    # everyday 11AM (UTC)
    - cron: '* 9 * * *'
```

**Comment by ynojima** [comment]
Thank you for pointing out! I fixed it.
